#!/usr/bin/env python3
"""Generate TypeScript bootstrap observations from trusted native run.sh captures."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


CAPTURES = {
    "zbot_side_moving.pth": ("side-moving.json", 1),
    "zbot_forward_moving.pth": ("forward-moving.json", 1),
    "ZBotStandUp.pth": ("stand-up.json", 1),
    "last_ZBotFootDown_ep_2500_rew_970.54364.pth": ("foot-down.json", 1),
    "ZBotSingleLeg.pth": ("single-leg.json", 2),
    "ZBotSnakeAndBipedal.pth": ("snake-and-bipedal.json", 1),
    "ZBotBipedalWalking_BigFoot.pth": ("bipedal-bigfoot.json", 2),
    "ZBotBipedalWalking_BigFoot_8DOF.pth": ("bipedal-bigfoot-8dof.json", 2),
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--captures", type=Path, default=Path("results/run-sh"))
    parser.add_argument("--output", type=Path, default=Path("src/rl/runShBootstrap.ts"))
    args = parser.parse_args()
    values = {}
    for checkpoint, (filename, count) in CAPTURES.items():
        capture = json.loads((args.captures / filename).read_text())
        observations = [step["obs_after"] for step in capture["effective_steps"][:count]]
        if len(observations) != count or any(len(obs) != len(capture["initial_env_reset_obs"]) for obs in observations):
            raise ValueError(f"invalid capture {filename}")
        values[checkpoint] = observations
    text = "// Generated by scripts/generate-run-sh-bootstrap.py from native Isaac Gym captures.\n"
    text += "export const RUN_SH_BOOTSTRAP: Record<string, number[][]> = "
    text += json.dumps(values, indent=2, sort_keys=True) + ";\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"generated {args.output}: {len(values)} run.sh tasks")


if __name__ == "__main__":
    main()
